/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/scene.gltf -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh name="leftFront" geometry={nodes.leftFront.geometry} material={materials.Bench} />
      <mesh name="leftMiddle" geometry={nodes.leftMiddle.geometry} material={materials.Bench} />
      <mesh name="leftBack" geometry={nodes.leftBack.geometry} material={materials.Bench} />
      <mesh name="shelf1" geometry={nodes.shelf1.geometry} material={materials.Stool} />
      <mesh name="shelf2" geometry={nodes.shelf2.geometry} material={materials.Stool2} />
      <mesh name="chair" geometry={nodes.chair.geometry} material={materials.Chair} />
      <mesh name="littleBowlLeft" geometry={nodes.littleBowlLeft.geometry} material={materials.Wood} />
      <mesh name="bigBowlLeft" geometry={nodes.bigBowlLeft.geometry} material={materials.Wood} />
      <mesh name="littleBowlRight" geometry={nodes.littleBowlRight.geometry} material={materials.Wood} />
      <mesh name="bigBowlRight" geometry={nodes.bigBowlRight.geometry} material={materials.Wood} />
      <mesh name="bigBowlRight001" geometry={nodes.bigBowlRight001.geometry} material={materials.Wood} />
      <mesh name="leftFront001" geometry={nodes.leftFront001.geometry} material={materials.Bench} />
      <mesh name="leftMiddle001" geometry={nodes.leftMiddle001.geometry} material={materials.Bench} />
      <mesh name="leftBack001" geometry={nodes.leftBack001.geometry} material={materials.Bench} />
      <mesh name="poleOne" geometry={nodes.poleOne.geometry} material={materials['Wood.002']} />
      <mesh name="poleTwo" geometry={nodes.poleTwo.geometry} material={materials['Wood.002']} />
      <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials.DefaultRoom} />
      <mesh name="Cube005_1" geometry={nodes.Cube005_1.geometry} material={materials['Grey Parquet']} />
      <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials.Inside} />
      <mesh name="Cube004_1" geometry={nodes.Cube004_1.geometry} material={materials.Default} />
      <mesh name="Cylinder078" geometry={nodes.Cylinder078.geometry} material={materials['Metallic.White']} />
      <mesh name="Cylinder078_1" geometry={nodes.Cylinder078_1.geometry} material={materials['White.Plastic']} />
      <mesh name="Cylinder078_2" geometry={nodes.Cylinder078_2.geometry} material={materials['Lights.Warm']} />
      <mesh name="Cylinder078_3" geometry={nodes.Cylinder078_3.geometry} material={materials['Gloss.Dark']} />
      <mesh name="Cylinder078_4" geometry={nodes.Cylinder078_4.geometry} material={materials['Metallic.White.001']} />
      <mesh name="Cylinder078_5" geometry={nodes.Cylinder078_5.geometry} material={materials.lamp} />
      <mesh name="Mesh001" geometry={nodes.Mesh001.geometry} material={materials.cable} />
      <mesh name="Mesh001_1" geometry={nodes.Mesh001_1.geometry} material={materials.lamp} />
      <mesh name="Mesh002" geometry={nodes.Mesh002.geometry} material={materials.cable} />
      <mesh name="Mesh002_1" geometry={nodes.Mesh002_1.geometry} material={materials.lamp} />
      <mesh name="Cylinder079" geometry={nodes.Cylinder079.geometry} material={materials['Metallic.White']} />
      <mesh name="Cylinder079_1" geometry={nodes.Cylinder079_1.geometry} material={materials['White.Plastic']} />
      <mesh name="Cylinder079_2" geometry={nodes.Cylinder079_2.geometry} material={materials['Lights.Warm']} />
      <mesh name="Cylinder079_3" geometry={nodes.Cylinder079_3.geometry} material={materials['Gloss.Dark']} />
      <mesh name="Cylinder079_4" geometry={nodes.Cylinder079_4.geometry} material={materials['Metallic.White.001']} />
      <mesh name="Cylinder079_5" geometry={nodes.Cylinder079_5.geometry} material={materials.lamp} />
      <mesh name="Cylinder080" geometry={nodes.Cylinder080.geometry} material={materials['Metallic.White']} />
      <mesh name="Cylinder080_1" geometry={nodes.Cylinder080_1.geometry} material={materials['White.Plastic']} />
      <mesh name="Cylinder080_2" geometry={nodes.Cylinder080_2.geometry} material={materials['Lights.Warm']} />
      <mesh name="Cylinder080_3" geometry={nodes.Cylinder080_3.geometry} material={materials['Gloss.Dark']} />
      <mesh name="Cylinder080_4" geometry={nodes.Cylinder080_4.geometry} material={materials['Metallic.White.001']} />
      <mesh name="Cylinder080_5" geometry={nodes.Cylinder080_5.geometry} material={materials.lamp} />
      <mesh name="Cylinder081" geometry={nodes.Cylinder081.geometry} material={materials['Metallic.White']} />
      <mesh name="Cylinder081_1" geometry={nodes.Cylinder081_1.geometry} material={materials['White.Plastic']} />
      <mesh name="Cylinder081_2" geometry={nodes.Cylinder081_2.geometry} material={materials['Lights.Warm']} />
      <mesh name="Cylinder081_3" geometry={nodes.Cylinder081_3.geometry} material={materials['Gloss.Dark']} />
      <mesh name="Cylinder081_4" geometry={nodes.Cylinder081_4.geometry} material={materials['Metallic.White.001']} />
      <mesh name="Cylinder081_5" geometry={nodes.Cylinder081_5.geometry} material={materials.lamp} />
      <mesh name="Mesh003" geometry={nodes.Mesh003.geometry} material={materials.cable} />
      <mesh name="Mesh003_1" geometry={nodes.Mesh003_1.geometry} material={materials.lamp} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
